version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
        interval: "daily"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "ember-cli"
    versioning-strategy: "widen"
    open-pull-requests-limit: 2